site_name: pymiro
site_url: https://LikhinMN.github.io/pymiro
repo_url: https://github.com/LikhinMN/pymiro

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src, .]
          options:
            show_root_heading: true
            show_source: true
            show_signature_annotations: true
            separate_signature: true

nav:
  - Home: index.md
  - Core API:
      - App & Reactivity: api/core.md
  - Components:
      - Layout: api/components/layout.md
      - Typography: api/components/typography.md
      - Input: api/components/input.md
      - Feedback: api/components/feedback.md
      - Navigation: api/components/navigation.md
